name: CI/CD - Maven + Docker + Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t nheinroth27/spring-boot-app-prueba:latest .

      - name: Push Docker image
        run: docker push nheinroth27/spring-boot-app-prueba:latest

      - name: Probar conexión SSH con mensaje
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: echo "✅ Conexión exitosa desde GitHub Actions"


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            docker stop spring-prueba || true
            docker rm spring-prueba || true
            docker pull nheinroth27/spring-boot-app-prueba:latest
            docker run -d --name spring-prueba -p 8080:8080 nheinroth27/spring-boot-app-prueba:latest
