name: SSH Debug

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar fingerprint de la clave privada usada
        run: |
          echo "$DROPLET_SSH_KEY" > id_rsa
          chmod 600 id_rsa
          echo "📎 Fingerprint de la clave cargada en secreto:"
          ssh-keygen -lf id_rsa
        env:
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Probar conexión SSH básica
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            echo "✅ Conexión SSH desde Actions funcionando correctamente"
            whoami
            uptime
