name: SSH Debug (Base64)

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Decodificar clave privada desde secreto base64
        run: |
          echo "$DROPLET_SSH_KEY_B64" | base64 -d > id_rsa
          chmod 600 id_rsa
          echo "📎 Fingerprint de la clave cargada en GitHub:"
          ssh-keygen -lf id_rsa
        env:
          DROPLET_SSH_KEY_B64: ${{ secrets.DROPLET_SSH_KEY_B64 }}

      - name: Conexión SSH directa (sin appleboy)
        run: |
          echo "⏳ Intentando conexión manual..."
          ssh -o StrictHostKeyChecking=no -i id_rsa root@${{ secrets.DROPLET_IP }} "
            echo '✅ Conexión directa exitosa desde GitHub Actions'
            whoami
            uptime
          "
        env:
          DROPLET_SSH_KEY_B64: ${{ secrets.DROPLET_SSH_KEY_B64 }}
